version: '3.2'
services:
  ngrok:
    image: wernight/ngrok
    network_mode: "host"
    stdin_open: true
    tty: true
    environment:
      NGROK_PORT: ${PORT}
  lunch-roulette:
    build:
      context: .
    environment:
      - PORT=${PORT}
      - DB_DIRECTORY=database
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - type: bind
        target: /database
        source: ./database
      - type: bind
        target: /.env
        source: .env
